name: REC
favicon: null
layout_spectrum: 0.3496549902483821
typography_spectrum: 0.24247996089980006
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9640340956393629
  lightness: 0.3432494839653373
  saturation: 0.9988874576520175
  rhythmicContrast: 0.010957090649753809
purpose: []
